### ISSUE TITLE
Server code is not published

### ISSUE THREAD

**Issue by LukasMiedema** [MelcherSt/UnifiedInstallationTool#1]
This breaks my workflow

**Comment by MelcherSt** [comment]
Sorry to hear this breaks your workflow. We're currently in the process of finding a suitable fix for your problem. Stay tuned.

**Comment by MelcherSt** [comment]
I believe the following site may be the solution to your problem; https://github.com/MelcherSt/UnifiedInstallationPlatform. Please let me know whether this information was helpful to you.

**Comment by LukasMiedema** [comment]
Thank you!
